# Generated by Django 4.0.5 on 2022-06-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao_cryptomoedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOEDA_BASE', models.CharField(choices=[('BTC', 'Bitcoin'), ('USD', 'Dolar Americano'), ('BRL', 'Real Brasileiro')], default='USD', max_length=3)),
                ('MOEDA_A_ACOMPANHAR', models.CharField(choices=[('BTC', 'Bitcoin'), ('USD', 'Dolar Americano'), ('BRL', 'Real Brasileiro'), ('EUR', 'Euro'), ('LTC', 'Litecoin'), ('ETH', 'Ethereum'), ('DOGE', 'Dogecoin'), ('XRP', 'XRP')], default='BTC', max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
