# Generated by Django 4.0.5 on 2022-07-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao_cryptomoedas', '0002_moeda_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='moeda',
            name='VALOR_DA_MOEDA',
            field=models.CharField(choices=[('20.309', '20.309'), ('20.309', 'Valor do dolar'), ('5.3866', 'Valor do Real Brasileiro'), ('1.0264', 'Valor do Euro'), ('228.533', 'Valor do Litecoin'), ('0.06753', 'Valor do Dogecoin'), ('0.32629', 'Valor do XRP')], default='20.309', max_length=100),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='MOEDA_A_ACOMPANHAR',
            field=models.CharField(choices=[('BTC', 'BTC'), ('USD', 'Dolar Americano'), ('BRL', 'Real Brasileiro'), ('EUR', 'Euro'), ('LTC', 'Litecoin'), ('ETH', 'Ethereum'), ('DOGE', 'Dogecoin'), ('XRP', 'XRP')], default='BTC', max_length=20),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='MOEDA_BASE',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('USD', 'Dolar Americano'), ('BRL', 'Real Brasileiro')], default='USD', max_length=20),
        ),
    ]
