# Generated by Django 4.0.5 on 2022-07-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao_cryptomoedas', '0005_moeda_data_da_moeda_alter_moeda_moeda_a_acompanhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='DATA_DA_MOEDA',
            field=models.CharField(choices=[('2022-07-06 19:38:43', '2022-07-06 19:38:43'), ('2022-07-06 18:30:42', '2022-07-06 18:30:42'), ('2022-07-06 19:38:12', '2022-07-06 19:38:12'), ('2022-07-06 19:38:23', '2022-07-06 19:38:23'), ('2021-09-06 04:32:37', '2021-09-06 04:32:37'), ('2022-07-06 19:38:30', '2022-07-06 19:38:30'), ('2022-07-06 19:38:44', '2022-07-06 19:38:44')], default='BTC', max_length=100),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='VALOR_DA_MOEDA',
            field=models.CharField(choices=[('BTC', '20.458'), ('BRL', '5.4294'), ('EUR', '1.0185'), ('ETH', '1.18769'), ('LTC', '228.533'), ('DOGE', '0.06853'), ('XRP', '0.32992')], default='BTC', max_length=100),
        ),
    ]
