# Generated by Django 4.0.5 on 2022-07-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao_cryptomoedas', '0006_alter_moeda_data_da_moeda_alter_moeda_valor_da_moeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moeda',
            name='DATA_DA_MOEDA',
            field=models.CharField(choices=[('2022-07-06 20:15:57', '2022-07-06 20:15:57'), ('2022-07-06 18:30:42', '2022-07-06 18:30:42'), ('2022-07-06 20:16:00', '2022-07-06 20:16:00'), ('2022-07-06 20:16:00', '2022-07-06 20:16:00'), ('2021-09-06 04:32:37', '2021-09-06 04:32:37'), ('2022-07-06 20:15:31', '2022-07-06 20:15:31'), ('2022-07-06 20:15:55', '2022-07-06 20:15:55')], max_length=100),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='VALOR_DA_MOEDA',
            field=models.CharField(choices=[('BTC', '20.596'), ('BRL', '5.4294'), ('EUR', '1.0181'), ('ETH', '1.19561'), ('LTC', '228.533'), ('DOGE', '0.06898'), ('XRP', '0.33253')], default='BTC', max_length=100),
        ),
    ]
