# Generated by Django 4.0.5 on 2022-07-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao_cryptomoedas', '0008_alter_moeda_data_da_moeda_alter_moeda_moeda_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moeda',
            name='DATA_DA_MOEDA',
        ),
        migrations.AlterField(
            model_name='moeda',
            name='VALOR_DA_MOEDA',
            field=models.CharField(choices=[('BTC', '20.605'), ('BRL', '5.4294'), ('EUR', '1.0184'), ('ETH', '1.19566'), ('LTC', '228.533'), ('DOGE', '0.06894'), ('XRP', '0.33329')], default='BTC', max_length=100),
        ),
    ]
